//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_TRAB
    {
        public decimal ID_ACT_TRAB { get; set; }
        public decimal ID_ASISTENTE { get; set; }
        public decimal ID_ACTIVIDAD { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual ASISTENTE ASISTENTE { get; set; }
    }
}
