//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENTE
    {
        public ASISTENTE()
        {
            this.ACT_TRAB = new HashSet<ACT_TRAB>();
        }
    
        public decimal ID_ASISTENTE { get; set; }
        public string RUT_TRABAJADOR { get; set; }
        public string NOMBRE { get; set; }
        public string AP_PAT { get; set; }
        public string AP_MAT { get; set; }
        public decimal NUM_ACCIDENTE { get; set; }
        public decimal NUM_ACC_POST_CAP { get; set; }
        public Nullable<System.DateTime> FEC_CAPACITACION { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public decimal ID_GENERO { get; set; }
        public decimal ID_COMUNA { get; set; }
    
        public virtual ICollection<ACT_TRAB> ACT_TRAB { get; set; }
        public virtual CLIENTE_EMPRESA CLIENTE_EMPRESA { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual GENERO GENERO { get; set; }
    }
}
