//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKLIST
    {
        public CHECKLIST()
        {
            this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
        }
    
        public decimal ID_CHECK { get; set; }
        public string NOMBRE_RIESGO { get; set; }
        public string OBSERVACION { get; set; }
        public decimal ID_EST_CHECK { get; set; }
        public decimal ID_CLIENTE { get; set; }
    
        public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual CLIENTE_EMPRESA CLIENTE_EMPRESA { get; set; }
        public virtual ESTADO_CHECK ESTADO_CHECK { get; set; }
    }
}
