//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public COMUNA()
        {
            this.ASISTENTE = new HashSet<ASISTENTE>();
            this.CLIENTE_EMPRESA = new HashSet<CLIENTE_EMPRESA>();
            this.PROFESIONAL = new HashSet<PROFESIONAL>();
        }
    
        public decimal ID_COMUNA { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_REGION { get; set; }
    
        public virtual ICollection<ASISTENTE> ASISTENTE { get; set; }
        public virtual ICollection<CLIENTE_EMPRESA> CLIENTE_EMPRESA { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual ICollection<PROFESIONAL> PROFESIONAL { get; set; }
    }
}
