//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public CONTRATO()
        {
            this.CONTRATO_PLAN = new HashSet<CONTRATO_PLAN>();
            this.CONTRATO_SERVICIO = new HashSet<CONTRATO_SERVICIO>();
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public string COD_CONTRATO { get; set; }
        public System.DateTime FECH_INICIO { get; set; }
        public decimal MONTO_PAGO { get; set; }
        public Nullable<System.DateTime> FECH_VENCIMIENTO { get; set; }
        public decimal ID_CLIENTE { get; set; }
    
        public virtual CLIENTE_EMPRESA CLIENTE_EMPRESA { get; set; }
        public virtual ICollection<CONTRATO_PLAN> CONTRATO_PLAN { get; set; }
        public virtual ICollection<CONTRATO_SERVICIO> CONTRATO_SERVICIO { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
