//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_CLIENTE
    {
        public ESTADO_CLIENTE()
        {
            this.CLIENTE_EMPRESA = new HashSet<CLIENTE_EMPRESA>();
        }
    
        public decimal ID_EST_CLIENT { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<CLIENTE_EMPRESA> CLIENTE_EMPRESA { get; set; }
    }
}
