//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_FACTURA
    {
        public ESTADO_FACTURA()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public decimal ID_EST_FACT { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
