//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
        }
    
        public decimal NUM_FACTURA { get; set; }
        public decimal MONTO_BASE { get; set; }
        public System.DateTime FECH_EMISION { get; set; }
        public System.DateTime FECH_VENC { get; set; }
        public decimal MONTO_EXTRA { get; set; }
        public decimal MONTO_MORA { get; set; }
        public decimal MONTO_TOTAL { get; set; }
        public string COD_CONTRATO { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public decimal ID_EST_FACT { get; set; }
    
        public virtual CLIENTE_EMPRESA CLIENTE_EMPRESA { get; set; }
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual ESTADO_FACTURA ESTADO_FACTURA { get; set; }
    }
}
