//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERO
    {
        public GENERO()
        {
            this.ASISTENTE = new HashSet<ASISTENTE>();
            this.PROFESIONAL = new HashSet<PROFESIONAL>();
        }
    
        public decimal ID_GENERO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<ASISTENTE> ASISTENTE { get; set; }
        public virtual ICollection<PROFESIONAL> PROFESIONAL { get; set; }
    }
}
