//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN_FAIL
    {
        public decimal ID_FAIL { get; set; }
        public string USER_FAIL { get; set; }
        public string PASS_FAIL { get; set; }
        public System.DateTime FECHA_INTENTO { get; set; }
    }
}
