//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public MATERIAL()
        {
            this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
        }
    
        public string COD_MATERIAL { get; set; }
        public string NOMBRE { get; set; }
        public decimal CANT_DISPONIBLE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
    }
}
