//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS
    {
        public PAIS()
        {
            this.REGION = new HashSet<REGION>();
        }
    
        public decimal ID_PAIS { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<REGION> REGION { get; set; }
    }
}
