//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN
    {
        public PLAN()
        {
            this.CONTRATO_PLAN = new HashSet<CONTRATO_PLAN>();
            this.PLAN_SERVICIO = new HashSet<PLAN_SERVICIO>();
        }
    
        public decimal ID_PLAN { get; set; }
        public string NOMBRE_PLAN { get; set; }
        public decimal PRECIO { get; set; }
        public System.DateTime FEC_INI_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FEC_FIN_VIGENCIA { get; set; }
    
        public virtual ICollection<CONTRATO_PLAN> CONTRATO_PLAN { get; set; }
        public virtual ICollection<PLAN_SERVICIO> PLAN_SERVICIO { get; set; }
    }
}
