//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESIONAL
    {
        public PROFESIONAL()
        {
            this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
            this.CREDENCIAL = new HashSet<CREDENCIAL>();
            this.REP_PROFESIONAL = new HashSet<REP_PROFESIONAL>();
        }
    
        public decimal ID_PROFESIONAL { get; set; }
        public string RUT_PROFESIONAL { get; set; }
        public string NOMBRE { get; set; }
        public string AP_PAT { get; set; }
        public string AP_MAT { get; set; }
        public System.DateTime FEC_NACIMIENTO { get; set; }
        public decimal TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
        public decimal ID_GENERO { get; set; }
        public decimal ID_COMUNA { get; set; }
    
        public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<CREDENCIAL> CREDENCIAL { get; set; }
        public virtual GENERO GENERO { get; set; }
        public virtual ICollection<REP_PROFESIONAL> REP_PROFESIONAL { get; set; }
    }
}
