//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_ERROR
    {
        public decimal ID_ERROR { get; set; }
        public string PROCEDIMIENTO { get; set; }
        public string COD_ERROR_DB { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA { get; set; }
    }
}
