//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.COMUNA = new HashSet<COMUNA>();
        }
    
        public decimal ID_REGION { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_PAIS { get; set; }
    
        public virtual ICollection<COMUNA> COMUNA { get; set; }
        public virtual PAIS PAIS { get; set; }
    }
}
