//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_CLI_EMP
    {
        public decimal ID_REP_CLIEMP { get; set; }
        public decimal NUM_VISITAS { get; set; }
        public decimal NUM_CAP { get; set; }
        public decimal NUM_ASESORIA { get; set; }
        public decimal NUM_LLAMADA { get; set; }
        public decimal CANT_NVA_IMPLEMEN { get; set; }
        public decimal N_ACC_PRE_CAP { get; set; }
        public decimal N_ACC_POST_CAP { get; set; }
        public decimal N_MULTA { get; set; }
        public decimal N_DEMANDA { get; set; }
        public decimal N_DIA_PERDIDO { get; set; }
        public decimal MONTO_COTIZACION { get; set; }
        public decimal ID_CLIENTE { get; set; }
    
        public virtual CLIENTE_EMPRESA CLIENTE_EMPRESA { get; set; }
    }
}
